### ISSUE TITLE
bugs with some blocks

### ISSUE THREAD

**Issue by FlorentLabrune** [ThatOneBepis/Infinitodustry-legacy#53]
I have some issues with some blocks in your mod. The texture isn't displayed in the tech tree as you can see in this pic : 
![bug_in_tree](https://user-images.githubusercontent.com/19490379/73355578-b8bbd080-4298-11ea-958f-b5317ac72682.png)

When I am on the scaled forest map I can't see some blocks (just under the core):
![bug_in_game](https://user-images.githubusercontent.com/19490379/73355632-dee17080-4298-11ea-8438-d1d58e76d9b0.png)
and when I click on it, the game crash. Here is the report :

> java.lang.NullPointerException
	at mindustry.input.InputHandler.tileTapped(InputHandler.java:598)
	at mindustry.input.DesktopInput.pollInput(DesktopInput.java:377)
	at mindustry.input.DesktopInput.update(DesktopInput.java:170)
	at mindustry.core.Control.update(Control.java:434)
	at arc.ApplicationCore.update(ApplicationCore.java:36)
	at mindustry.ClientLauncher.update(ClientLauncher.java:136)
	at arc.backend.sdl.SdlApplication.listen(SdlApplication.java:158)
	at arc.backend.sdl.SdlApplication.loop(SdlApplication.java:146)
	at arc.backend.sdl.SdlApplication.<init>(SdlApplication.java:52)
	at mindustry.desktop.DesktopLauncher.main(DesktopLauncher.java:46)

Except this, your mod is awesome ! Nice job !

**Comment by ThatOneBepis** [comment]
for the drills, i am aware its a thing but not why its a thing, and for blocks... lets just say i haven't though out of their possible sprites

**Comment by FlorentLabrune** [comment]
Yeah I just saw that there is no sprites for those blocks, so I'll wait ! thx for the quick answer

**Comment by ThatOneBepis** [comment]
Update: Will update the map to remove the drills that may interfere, causing the issue. As for sprites, it will come later
